name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirement.txt

      - name: Run flake8 linter
        run: |
          echo "Running flake8..."
          flake8 .

      - name: Run pytest
        run: |
          echo "Running pytest..."
          pytest

      - name: Set up Heroku
        run: |
          echo "Setting up Heroku CLI..."
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Log in to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Logging in to Heroku..."
          echo $HEROKU_API_KEY | heroku auth:token | docker login --username=_ --password-stdin registry.heroku.com

      - name: Deploy to Heroku using Git
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Deploying to Heroku using Git..."
          git remote add heroku https://git.heroku.com/${{ secrets.HEROKU_APP_NAME }}.git
          heroku auth:token
          git push heroku main
