name: Deploy to Koyeb

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 linter
        run: |
          echo "Running flake8..."
          flake8 .

      - name: Run pytest
        run: |
          echo "Running pytest..."
          pytest

      - name: Log in to Docker Hub
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
        run: |
          echo "Logging into Docker Hub..."
          echo $DOCKER_PASSWORD | docker login --username $DOCKER_USERNAME --password-stdin

      - name: Build Docker container
        run: |
          echo "Building Docker container..."
          docker build -t ${{ secrets.DOCKER_USERNAME }}/houseproj:latest .

      - name: Push Docker container to Docker Hub
        run: |
          echo "Pushing Docker container to Docker Hub..."
          docker push ${{ secrets.DOCKER_USERNAME }}/houseproj:latest

      - name: Install Koyeb CLI
        run: |
          echo "Installing Koyeb CLI..."
          wget https://github.com/koyeb/koyeb-cli/releases/download/v4.3.0/koyeb-cli_4.3.0_linux_amd64.tar.gz
          tar -xzf koyeb-cli_4.3.0_linux_amd64.tar.gz
          sudo mv koyeb /usr/local/bin/koyeb
          echo 'export PATH=$PATH:/usr/local/bin/koyeb' >> $GITHUB_ENV

      - name: Deploy to Koyeb
        env:
          KOYEBHPKEY: ${{ secrets.KOYEBHPKEY }}
        run: |
          echo "Deploying to Koyeb..."
          koyeb service update houseproj --image ${{ secrets.DOCKER_USERNAME }}/houseproj:latest --api-key $KOYEBHPKEY