name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.7' # Specify your Python version here

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run flake8 linter
        run: |
          echo "Running flake8..."
          flake8 .

      - name: Run pytest
        run: |
          echo "Running pytest..."
          pytest

      - name: Log in to Heroku Docker Registry
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Logging into Heroku Docker Registry..."
          echo $HEROKU_API_KEY | docker login --username=_ --password-stdin registry.heroku.com

      - name: Build Docker container
        run: |
          echo "Building Docker container..."
          docker build -t registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web .

      - name: Push Docker container to Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Pushing Docker container..."
          docker push registry.heroku.com/${{ secrets.HEROKU_APP_NAME }}/web

      - name: Release Heroku app
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Releasing Heroku app..."
          heroku container:release web --app ${{ secrets.HEROKU_APP_NAME }}

      - name: Set up Heroku CLI
        run: |
          echo "Setting up Heroku CLI..."
          curl https://cli-assets.heroku.com/install.sh | sh

      - name: Authenticate with Heroku
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Authenticating with Heroku..."
          echo $HEROKU_API_KEY | heroku auth:token | docker login --username=_ --password-stdin registry.heroku.com

      - name: Add Heroku remote
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "Adding Heroku remote..."
          heroku git:remote -a ${{ secrets.HEROKU_APP_NAME }}

      - name: Deploy to Heroku using Git
        run: |
          echo "Deploying to Heroku using Git..."
          git push heroku main
